### PR TITLE
Drop Python 3.6 support

### PR DESCRIPTION
**Pull request by marcelm**
Python 3.6 is end-of-life and there have recently been new releases of
Python 3.7+ that fix security issues:
https://discuss.python.org/t/14353

Python 3.6 did not get these fixes, so it seems a good idea to stop using
and/or supporting it.

### CODE REVIEW

**Comment by rhpvorderman** [comment]
Python-isal will also not be able to use versions older than 3.7 due to `METH_FASTCALL` being introduced in 3.7. (When I made that PR 3.6 had been unsupported for a few weeks). So when I will release python-isal 1.0 everything still running 3.6 will break. I am all for this change!

Incidentally this also means the default settings of CIBuildWheel can be used as regards to the container used.

**Comment by marcelm** [comment]
> Incidentally this also means the default settings of CIBuildWheel can be used as regards to the container used.

What do you mean?

**Comment by rhpvorderman** [comment]
I was thinking of this https://github.com/marcelm/dnaio/pull/28#issuecomment-1013158275 . But I see now that refers to a version of pip, not to python 3.6. I misremembered, sorry.

**Comment by marcelm** [comment]
Ah, but you’re right: Ubuntu 18.04 doesn’t have Python 3.6 either, so we give that up anyway and that means we can now bump the cibuildwheel version. I’ll add that to this PR.

**Comment by rhpvorderman** [comment]
Okay great!

**Pull request merged**
