### PR TITLE
Add Sphinx configuration

### PR DESCRIPTION
**Pull request by marcelm**
This is preliminary configuration for Sphinx that generates some API documentation. This is far from complete.

I had this in a local branch that I started last year. I’ll merge this right away so I can setup the project in Read the Docs.

### CODE REVIEW

**Comment by marcelm** [comment]
There we go: https://dnaio.readthedocs.io/en/latest/

**Comment by rhpvorderman** [comment]
Great!

**Comment by rhpvorderman** [comment]
@marcelm I did notice that the API documentation does not show up on dnaio.readthedocs.io. Was the requirements file properly installed in the environment? There is a setting for that.

**Comment by marcelm** [comment]
I know, I was working on something and broke it. Should be fixed now.

**Pull request merged**
