### PR TITLE
Rename (Bytes-)Sequence to (Bytes-)SequenceRecord

### LINKED ISSUE #36: Consider renaming Sequence to SequenceRecord
This has bothered me for a long time: A `Sequence` isn’t actually just a sequence; it is an object containing a sequence of nucleotides, a sequence of quality values and a name. The misnaming becomes obvious when one considers that a `Sequence` has a `sequence` attribute, so I’m sometimes tempted to write something like `s = sequence.sequence` or similar.

Biopython has `SeqRecord`, but I don’t like abbreviations in class names and to reduce the risk of being confusing with the Biopython class, I think it should be `SequenceRecord`.

### PR DESCRIPTION
**Pull request by marcelm**
Work in progress.

To Do:
- [x] Add the `Sequence` and `BytesSequence` aliases
- [x] Add tests for the aliases

For better testing, l’ll change this so that in the first step, the classes are renamed and aliases are added, but that the tests use the old names. Then I’ll change the tests to use the new names and add some tests for the old names.

Closes #36

### CODE REVIEW

**Comment by marcelm** [comment]
I have added tests and moved all tests for the sequence classes to a separate module. Ready for review.

**Review by rhpvorderman — APPROVED** [review]
Looks good to me! One nitpick, `test_sequence.py` should probably be called `test_sequence_record.py`.

**Comment by marcelm** [comment]
Since it also tests `BytesSequenceRecord`, I renamed it to `test_records.py` now.

**Comment by rhpvorderman** [comment]
Great, much better naming!

**Pull request merged**
